### PR TITLE
Add element at random location

### PR DESCRIPTION
**Pull request by p4bl1t0**
Add a random index to insert the new element in order to see differents magicmoves animation

### CODE REVIEW

**Comment by maccman** [comment]
Good stuff!

**Comment by maccman** [comment]
Oops, this isn't working for me. Reverting till I find out why.

**Comment by p4bl1t0** [comment]
I tested it in lastest Chrome and lastest Firefox and works fine for me.

What problem do you experiment?

I couldn't tested on IE 9 because I am on a Linux platform

**Comment by p4bl1t0** [comment]
More testing at http://p4bl1t0.github.io/jquery.magicmove/index.html
IE 10 : Works well
IE9: No animation and in original neither
Opera presto : Works well
Opera Webkit: Works well
Safari windows: Works well

Couldn't find where the issue is ...

**Pull request merged**
